#! /bin/sh
# Config by Solomon Thatcher
# https://github.com/SolomonThatcher

# Startup Notification
notify-send "Welcome back Solomon!"

# Polybar Launch Options
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor DP-2 -d I II III IV V VI VII
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7

bspc config border_width	2
bspc config window_gap		10

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

# Set correct color palete for system
shade1="#808080"
shade2="#00796B"
shade3="#00796B"
shade4="#808080"

bspc config normal_border_color ${shade1}
bspc config active_border_color ${shade2}
bspc config focused_border_color ${shade3}
bspc config presel_feedback_color ${shade4}
wname LG3D

# Start SXHKD
sxhkd &
xrdb -merge $HOME/.Xresources

# Display Settings
if [ -x /bin/own_script_bspwm_laptop_dual_monitor ];then
	own_script_bspwm_laptop_dual_monitor
fi

if [ -x $HOME/.config/polybar ]; then
	bash $HOME/.config/polybar/launch.sh
fi

# END
